<?php

class Translator
{
    private $lang;
    
    private $dictionary = [
        'uk' => [
            // Загальні
            'nav_features' => 'Можливості',
            'nav_for_whom' => 'Для кого',
            'nav_how' => 'Як це працює',
            'nav_analytics' => 'Аналітика',
            'status_online' => 'Онлайн',
            
            // HomePage
            'home_title' => 'ProHour - Система відстеження часу',
            'hero_h1_1' => 'Контролюйте час.',
            'hero_h1_2' => 'Організовуйте роботу.',
            'hero_h1_3' => 'Приймайте рішення.',
            'hero_p' => 'Задачі, проєкти, облік часу та аналітика — в одному просторі для компаній, команд та фрілансерів.',
            'hero_btn_tasks' => 'Відкрити задачі',
            'hero_btn_more' => 'Дізнатись більше',
            'features_badge' => 'Можливості системи',
            'features_h2' => 'Все необхідне для контролю часу',
            'f_time_h3' => 'Облік часу',
            'f_time_p' => 'Відстежуйте час виконання задач у реальному часі.',
            'f_proj_h3' => 'Проєкти',
            'f_proj_p' => 'Групуйте задачі по клієнтах та проєктах.',
            'f_tasks_h3' => 'Задачі',
            'f_tasks_p' => 'Контролюйте статуси задач та дедлайни.',
            'f_stat_h3' => 'Аналітика',
            'f_stat_p' => 'Аналізуйте продуктивність та навантаження.',
            'wf_badge' => 'Workflow',
            'wf_h2' => 'Простий процес роботи',
            'wf_1' => 'Клієнт',
            'wf_2' => 'Проєкт',
            'wf_3' => 'Задача',
            'wf_4' => 'Час',
            'stat_label_time' => 'Зафіксовано часу',
            'stat_label_tasks' => 'Активних задач',
            'stat_label_proj' => 'Активних проєктів',
            'fb_badge' => 'Зворотний зв’язок',
            'fb_h2' => 'Маєте питання?',
            'fb_p' => 'Напишіть нам повідомлення або залиште свій email.',
            'fb_ph_email' => 'Ваш email',
            'fb_ph_msg' => 'Ваше повідомлення',
            'fb_btn' => 'Надіслати',

            // TasksPage
            'tasks_title' => 'Мої задачі',
            'add_task' => 'Додати нову задачу',
            'task_name_ph' => 'Назва задачі (напр., Проєктування БД)',
            'btn_create' => 'Створити',
            'in_progress' => 'В процесі виконання 🚀',
            'btn_pause' => '⏸ Пауза',
            'btn_play' => '▶ Запустити',
            'all_tasks' => 'Усі задачі',
            'empty_list' => 'Список порожній. Час додати першу задачу!',
            'status_completed' => '✅ Завершено',
            'status_active' => '▶ В роботі',
            'status_paused' => '⏸ На паузі',
            'btn_edit' => 'Змінити',
            'btn_delete' => 'Видалити',
            'ph_new_name' => 'Нова назва',

            // ClientsPage
            'clients_title' => 'Клієнти | ProHour',
            'clients_eyebrow' => 'CRM модуль',
            'clients_hero_title' => 'Клієнти ProHour',
            'clients_hero_text' => 'Керуйте клієнтами, для яких команда створює проєкти, задачі та облік витраченого часу.',
            'clients_total' => 'Усього клієнтів',

            'clients_new_title' => 'Новий клієнт',
            'clients_new_text' => 'Додайте організацію або замовника, з яким пов’язані майбутні проєкти.',
            'clients_name' => 'Назва клієнта',
            'clients_name_ph' => 'Наприклад, NURE',
            'clients_contact_person' => 'Контактна особа',
            'clients_contact_person_ph' => 'Ім’я відповідальної особи',
            'clients_email' => 'Email',
            'clients_phone' => 'Телефон',
            'clients_description' => 'Опис',
            'clients_description_ph' => 'Короткий опис клієнта або умов співпраці',
            'clients_add_btn' => 'Додати клієнта',

            'clients_list_title' => 'Список клієнтів',
            'clients_list_text' => 'Перелік клієнтів, доступних для прив’язки до проєктів.',
            'clients_table_client' => 'Клієнт',
            'clients_table_contact' => 'Контактна особа',
            'clients_table_phone' => 'Телефон',
            'clients_table_action' => 'Дія',
            'clients_delete_btn' => 'Видалити',
            'clients_empty' => 'Клієнтів поки немає. Додайте першого клієнта через форму вище.',
            'clients_no_description' => 'Опис не вказано',

            'clients_err_name' => 'Назва клієнта не може бути порожньою.',
            'clients_err_email' => 'Введіть коректний email клієнта.',
            'clients_msg_created' => 'Клієнта успішно додано.',
            'clients_msg_create_failed' => 'Не вдалося додати клієнта.',
            'clients_msg_deleted' => 'Клієнта видалено.',
            'clients_msg_delete_failed' => 'Не вдалося видалити клієнта.',

            // ProjectsPage
            'projects_title' => 'Проєкти | ProHour',
            'projects_eyebrow' => 'Project Management',
            'projects_hero_title' => 'Проєкти ProHour',
            'projects_hero_text' => 'Керуйте проєктами команди, прив’язуйте їх до клієнтів і створюйте задачі в межах конкретного проєкту.',
            'projects_total' => 'Усього проєктів',

            'projects_new_title' => 'Новий проєкт',
            'projects_new_text' => 'Створіть проєкт для клієнта вашої команди.',
            'projects_name' => 'Назва проєкту',
            'projects_name_ph' => 'Наприклад, Розробка CRM-модуля',
            'projects_client' => 'Клієнт',
            'projects_no_client' => 'Без клієнта',
            'projects_status' => 'Статус',
            'projects_status_active' => 'Активний',
            'projects_status_paused' => 'На паузі',
            'projects_status_completed' => 'Завершений',
            'projects_description' => 'Опис',
            'projects_description_ph' => 'Короткий опис цілей, домовленостей або обсягу робіт',
            'projects_add_btn' => 'Додати проєкт',

            'projects_list_title' => 'Список проєктів',
            'projects_list_text' => 'Проєкти, доступні для створення та групування задач.',
            'projects_table_project' => 'Проєкт',
            'projects_table_client' => 'Клієнт',
            'projects_table_status' => 'Статус',
            'projects_table_created' => 'Створено',
            'projects_table_action' => 'Дія',
            'projects_delete_btn' => 'Видалити',
            'projects_empty' => 'Проєктів поки немає. Додайте перший проєкт через форму вище.',
            'projects_no_description' => 'Опис не вказано',

            'projects_err_name' => 'Назва проєкту не може бути порожньою.',
            'projects_msg_created' => 'Проєкт успішно додано.',
            'projects_msg_create_failed' => 'Не вдалося додати проєкт.',
            'projects_msg_deleted' => 'Проєкт видалено.',
            'projects_msg_delete_failed' => 'Не вдалося видалити проєкт.',
        ],
        'en' => [
            // Загальні
            'nav_features' => 'Features',
            'nav_for_whom' => 'For Whom',
            'nav_how' => 'How it works',
            'nav_analytics' => 'Analytics',
            'status_online' => 'Online',
            
            // HomePage
            'home_title' => 'ProHour - Time Tracking System',
            'hero_h1_1' => 'Control your time.',
            'hero_h1_2' => 'Organize your work.',
            'hero_h1_3' => 'Make decisions.',
            'hero_p' => 'Tasks, projects, time tracking, and analytics — in one workspace for companies, teams, and freelancers.',
            'hero_btn_tasks' => 'Open Tasks',
            'hero_btn_more' => 'Learn More',
            'features_badge' => 'System Features',
            'features_h2' => 'Everything you need to control time',
            'f_time_h3' => 'Time Tracking',
            'f_time_p' => 'Track task execution time in real-time.',
            'f_proj_h3' => 'Projects',
            'f_proj_p' => 'Group tasks by clients and projects.',
            'f_tasks_h3' => 'Tasks',
            'f_tasks_p' => 'Monitor task statuses and deadlines.',
            'f_stat_h3' => 'Analytics',
            'f_stat_p' => 'Analyze productivity and workload.',
            'wf_badge' => 'Workflow',
            'wf_h2' => 'Simple work process',
            'wf_1' => 'Client',
            'wf_2' => 'Project',
            'wf_3' => 'Task',
            'wf_4' => 'Time',
            'stat_label_time' => 'Tracked hours',
            'stat_label_tasks' => 'Active tasks',
            'stat_label_proj' => 'Active projects',
            'fb_badge' => 'Feedback',
            'fb_h2' => 'Have questions?',
            'fb_p' => 'Send us a message or leave your email.',
            'fb_ph_email' => 'Your email',
            'fb_ph_msg' => 'Your message',
            'fb_btn' => 'Send',

            // TasksPage
            'tasks_title' => 'My Tasks',
            'add_task' => 'Add new task',
            'task_name_ph' => 'Task name (e.g., DB Design)',
            'btn_create' => 'Create',
            'in_progress' => 'In Progress 🚀',
            'btn_pause' => '⏸ Pause',
            'btn_play' => '▶ Play',
            'all_tasks' => 'All Tasks',
            'empty_list' => 'List is empty. Time to add the first task!',
            'status_completed' => '✅ Completed',
            'status_active' => '▶ Active',
            'status_paused' => '⏸ Paused',
            'btn_edit' => 'Edit',
            'btn_delete' => 'Delete',
            'ph_new_name' => 'New name',

            // ClientsPage
            'clients_title' => 'Clients | ProHour',
            'clients_eyebrow' => 'CRM module',
            'clients_hero_title' => 'ProHour Clients',
            'clients_hero_text' => 'Manage clients for whom your team creates projects, tasks and time tracking records.',
            'clients_total' => 'Total clients',

            'clients_new_title' => 'New client',
            'clients_new_text' => 'Add an organization or customer linked to future projects.',
            'clients_name' => 'Client name',
            'clients_name_ph' => 'For example, NURE',
            'clients_contact_person' => 'Contact person',
            'clients_contact_person_ph' => 'Responsible person name',
            'clients_email' => 'Email',
            'clients_phone' => 'Phone',
            'clients_description' => 'Description',
            'clients_description_ph' => 'Short client description or cooperation notes',
            'clients_add_btn' => 'Add client',

            'clients_list_title' => 'Client list',
            'clients_list_text' => 'Clients available for linking to projects.',
            'clients_table_client' => 'Client',
            'clients_table_contact' => 'Contact person',
            'clients_table_phone' => 'Phone',
            'clients_table_action' => 'Action',
            'clients_delete_btn' => 'Delete',
            'clients_empty' => 'No clients yet. Add the first client using the form above.',
            'clients_no_description' => 'No description',

            'clients_err_name' => 'Client name cannot be empty.',
            'clients_err_email' => 'Enter a valid client email.',
            'clients_msg_created' => 'Client has been added successfully.',
            'clients_msg_create_failed' => 'Failed to add client.',
            'clients_msg_deleted' => 'Client has been deleted.',
            'clients_msg_delete_failed' => 'Failed to delete client.',

            // ProjectsPage
            'projects_title' => 'Projects | ProHour',
            'projects_eyebrow' => 'Project Management',
            'projects_hero_title' => 'ProHour Projects',
            'projects_hero_text' => 'Manage team projects, link them to clients and create tasks within a specific project.',
            'projects_total' => 'Total projects',

            'projects_new_title' => 'New project',
            'projects_new_text' => 'Create a project for a client of your team.',
            'projects_name' => 'Project name',
            'projects_name_ph' => 'For example, CRM module development',
            'projects_client' => 'Client',
            'projects_no_client' => 'No client',
            'projects_status' => 'Status',
            'projects_status_active' => 'Active',
            'projects_status_paused' => 'Paused',
            'projects_status_completed' => 'Completed',
            'projects_description' => 'Description',
            'projects_description_ph' => 'Short description of goals, agreements or scope of work',
            'projects_add_btn' => 'Add project',

            'projects_list_title' => 'Project list',
            'projects_list_text' => 'Projects available for task creation and grouping.',
            'projects_table_project' => 'Project',
            'projects_table_client' => 'Client',
            'projects_table_status' => 'Status',
            'projects_table_created' => 'Created',
            'projects_table_action' => 'Action',
            'projects_delete_btn' => 'Delete',
            'projects_empty' => 'No projects yet. Add the first project using the form above.',
            'projects_no_description' => 'No description',

            'projects_err_name' => 'Project name cannot be empty.',
            'projects_msg_created' => 'Project has been added successfully.',
            'projects_msg_create_failed' => 'Failed to add project.',
            'projects_msg_deleted' => 'Project has been deleted.',
            'projects_msg_delete_failed' => 'Failed to delete project.',
        ]
    ];

    public function __construct($lang = 'uk')
    {
        $this->lang = array_key_exists($lang, $this->dictionary) ? $lang : 'uk';
    }

    public function get($key)
    {
        return $this->dictionary[$this->lang][$key] ?? $key;
    }

    public function getLang()
    {
        return $this->lang;
    }
}